@Library('Shared') _
pipline{
  agent {lable 'dev-server'}

  stages{
    stage("Code clone"){
      stpes{
        clone("https://github.com/vinayakz/two-tier-flask-app.git","master")
      }
    }
    stage("Build"){
      steps{
        dockerbuild("notes-app","latest")
      }
    }
    stage("Push to DocekrHub"){
      steps{
        dockerpush("dockerHubCreds","notes-app","latest")
      }
    }
    stage("Deploy"){
      steps{
        deploy()
      }
    }
  }
}
